### PR TITLE
scholar hips 😂

### PR DESCRIPTION
**Pull request by nathany**
Preview: https://deploy-preview-19--womenwhogo.netlify.com/scholarships.html

### CODE REVIEW

**Review by carolynvs — APPROVED** [review]
hehe oops! Thanks for the fix

**Comment by nathany** [comment]
It doesn't appear to have deployed automagically.

**Comment by carolynvs** [comment]
Can you do a hard refresh? I see from our build logs that it deployed successfully and I am seeing the correct title now `<title>Scholarships - Women Who Go</title>`.

**Comment by nathany** [comment]
Hmm. I still see `GopherCon Scholarhips` below the logo. Both in Chrome and Safari, to be sure it wasn't a caching issue on my side.

**Comment by carolynvs** [comment]
omg, I am a dork! Thank you for checking, I misspelled it in more than one place... 🤦‍♀️

**Comment by nathany** [comment]
Whoops! I saw the typo in one spot, then corrected it in another spot without noticing what I was doing.

**Comment by nathany** [comment]
Shall I send another PR?

**Comment by carolynvs** [comment]
That would be so helpful! Thanks!

**Comment by nathany** [comment]
Done and done. #20.

Thanks Carolyn!

**Pull request merged**
